version: '3.9'

services:
  shiny:
    build: .
    #image: hicsail/comets_shinyapp:master
    container_name: shiny_app
    ports:
      - "3838:3838"
    restart: unless-stopped
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: shiny
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shiny
    ports:
      - "5432:5432"
    restart: unless-stopped